### ISSUE TITLE
Portal Effects Not Showing Up 1.17.1

### ISSUE THREAD

**Issue by AngelofWoe** [kyrptonaught/DatapackPortals#2]
On our 1.17.1 server, I have portals working just fine technically, and the little ring particle effects show up, but the background portal effect you step into isn't showing up in any color. I am attaching a screenshot of each end of the portal and my test data pack.

<img width="1792" alt="Screen Shot 2021-09-11 at 17 37 58" src="https://user-images.githubusercontent.com/6075018/132963243-c314d5fc-5637-475f-a27c-3d39651624db.png">
<img width="1792" alt="Screen Shot 2021-09-11 at 17 38 06" src="https://user-images.githubusercontent.com/6075018/132963246-6f50fa7a-55e8-4937-910c-34202d1203a3.png">
[endsandstoneportalpack.zip](https://github.com/kyrptonaught/DatapackPortals/files/7148608/endsandstoneportalpack.zip)

**Comment by kyrptonaught** [comment]
Are you using a vanilla client without the mod installed? The mod should be installed on the client as well to see the portals. The datapack is only required on the server though, it will sync. 

I do have a solution in the works for vanilla clients though

**Comment by AngelofWoe** [comment]
Thank you for reminding me. It had been a few months since my last test and I had completely forgotten about this problem and since I remembered it working before I had skipped reading the comments this time.

Thank you so much for your time.
