### ISSUE TITLE
[Request] Support bungeecord/velocity with `/server lobby` ?

### ISSUE THREAD

**Issue by gadget78** [kyrptonaught/DatapackPortals#8]
is it possible for this to support a Bungee/Velocity environment ? 
so portals can send players to different servers ?

**Comment by kyrptonaught** [comment]
Is this for 1.18 or 1.19? This requires a separate mod to be installed to add the velocity functionality.

**Comment by gadget78** [comment]
Indeed, I meant, could this be used, once you have the '/server' velocity functions in place ...

**Comment by kyrptonaught** [comment]
I do already have a mod for 1.18 that does this. I don't think I ported it to 1.19 yet.

The /server commands exists on the proxy not the server where the mod exists, so the mod must communicate with the proxy.

**Comment by gadget78** [comment]
> I do already have a mod for 1.18 that does this. I don't think I ported it to 1.19 yet.
> 
> The /server commands exists on the proxy not the server where the mod exists, so the mod must communicate with the proxy.

Is that this totally separate mod ..
[Here](https://github.com/kyrptonaught/VelocityServerSwitch)
Could that be incorporated into this mod ?
Can DataPackPortals perform commands as you enter them ?... 

Would be magic if possible....

**Comment by kyrptonaught** [comment]
I released 1.2.0 for 1.19 which includes support for portals running commands built in. If you're on 1.18 this used to be its own [addon ](https://github.com/kyrptonaught/CMD-Portals/releases) mod to datapack portals. 

See the [example portal](https://github.com/kyrptonaught/DatapackPortals/tree/1.19/examples/exampledatpack/data/exampledatapack/cmdportals).

Note you'll also need to use the other mod you linked for the server switching command itself. It has also been updated to 1.19

**Comment by gadget78** [comment]
We are running latest, so this would actually work then !!??... 
Will give this a go ! Thankyou ..

**Comment by gadget78** [comment]
well tried to get this working, the `velocityserverswitch` mod works.. 

but cannot get this DatapackPortals to work :( using `datapackportals-1.2.0-1.19.jar` there are no errors in logs... 
does it have any  dependences ? as in do i need the `customportalapi` ? (as i cannot see find that as a download)
have used your basic example, and my custom one, added the data pack, and thats showing up ok in `/datapack list`... and datapack is loading correctly looking at logs...

**Comment by kyrptonaught** [comment]
No it does not require any dependencies to be installed, if you check the logs customportalapi should already be there.

The example portal requires a frame to be made out of dirt and then lit with a stick. That didn't work?

**Comment by kyrptonaught** [comment]
Feel free to message me on discord:

Kyrptonaught#4239

**Comment by gadget78** [comment]
>
> No it does not require any dependencies to be installed, if you check the logs customportalapi should already be there.

checking logs, yes its present :) that ticks that off...

> 
> The example portal requires a frame to be made out of dirt and then lit with a stick. That didn't work?

i used your end portal example.. but indeed, doesn't do a thing, no errors or anything... 

>Feel free to message me on discord:

discord friend/message sent :) ...

**Comment by gadget78** [comment]
just to close this issue.... 
to fix above issues, you needed mod on client... 
but with this provided [mod](https://github.com/kyrptonaught/CustomPortalApi-Polymer) it works for vanilla clients (using nether/end portal data visuals)
also update have has fixed fabric proxy issues to :)  so all my additional requests been answered too !
problems clossed
