### ISSUE TITLE
Fabric 1.19.2 portals appear/animate but don't teleport

### ISSUE THREAD

**Issue by snatella** [kyrptonaught/DatapackPortals#9]
Using 
- minecraft (server) 1.19.2
- fabric-api-0.64.0+1.19.2
- datapackportals-1.2.1-1.19
- Multiworld-1.6 (self compiled, owner has not provided a 1.6 build)
- fantasy-0.4.7+1.19.2 (for multiworld)

Portals (seem to) link to the material frame, appear and shimmer when you stand in them, and you hear sound, but teleport never happens. Shimmer colour appears to work as well (though the portals all appear grey/black).

The world was created with multiworld using `/mw create guild:test2 NORMAL` and I can teleport into it using the /mw tp as well as command /execute etc. 

guildportal.json:
```
{
    "block": "minecraft:stone",
    "dim": "guild:test2",
    "r": 0,
    "g": 200,
    "b": 0,
    "ignitionType": "BLOCK",
    "ignitionSource": "minecraft:fire",
    "returnDim": "minecraft:overworld"
}
```

The logs do not indicate any trouble (no messages at all standing in portals).

Happy to do assist with more information.

**Comment by kyrptonaught** [comment]
Can you try adding this jar and see if this fixes it? 
(This is an update to CPA, the library under the hood of datapack portals, unzip it first)
[customportalapi-0.0.1-beta57-1.19.zip](https://github.com/kyrptonaught/DatapackPortals/files/10073039/customportalapi-0.0.1-beta57-1.19.zip)

**Comment by snatella** [comment]
Yup that fixes the portals! Thanks! Need me to do any further testing or shall I close?

**Comment by kyrptonaught** [comment]
Datapackportals 1.2.2 includes this version of CPA
